services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${STORE_USER:-user}
      POSTGRES_PASSWORD: ${STORE_PASSWORD:-password}
      POSTGRES_DB: ${STORE_DATABASE:-database}
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql
#    ports:
#      - "45432:5432"
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-database}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reviewer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - migrator
    ports:
      - "8080:8080"
    networks:
      - internal

  migrator:
    build:
      context: ./migrator
      dockerfile: Dockerfile
    command: "goose postgres \"host=${STORE_HOST:-database} user=${STORE_USER:-user} password=${STORE_PASSWORD:-password} dbname=${STORE_DATABASE:-database} sslmode=disable\" up"
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal

volumes:
  database_data:
    name: database_data

networks:
  internal:
    driver: bridge
    name: internal